### PR TITLE
Don't double-wrap callbacks.

### LINKED ISSUE #10: Somehow callbacks are being multiply-wrapped
I'm trying to debug a problem we're observing where we see a sudden explosion of fibers. The fibers are being created by meteor-promise. This problem is causing production outages on roughly an hourly basis.

What I've observed so far is that when the storm happens, the monkey-patched `Promise.then()` is being called and given inputs which are _already wrapped_ by `wrapCallback()` from `promise_server.js`. I determined this by instrumenting `wrapCallback()` to console.log() the callback. This printed:

    function (arg) {
      return fiberPool.run({
        callback: callback,
        args: [arg], // Avoid dealing with arguments objects.
        dynamics: dynamics,
        stackError: stackError,
      }, Promise);
    };

That code is, of course, the function that `wrapCallback()` returns! This confused me for a while because initially I assumed I had done my instrumentation wrong and printed the wrong thing. But, no -- `wrapCallback()` is in fact receiving as input a callback that it itself created.

How could this happen? My first thought was that somehow `makeCompatible()` had been called multiple times, repeatedly re-patching the same `Promise` definition. Hence, each patch would call the next's `.then()`, adding additional redundant wrappers. However, when I put a console.log() at the top of this function, I only saw it printed once.

I tried sampling stack traces when `wrapCallback()` is called in this redundant way, and AFAICT they all look like this:

     at wrapCallback (/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:117:20)
     at Promise.then (/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:25:9)
     at process._tickCallback (node.js:369:9)

Unfortunately, I do not know why `_tickCallback` is directly calling `Promise.then`. Presumably this means someone registered `Promise.then.bind(this, cb)` as a next-tick callback?

My current theory is that this monkey-patching is exhibiting a variation of "fragile base class syndrome": I suspect the V8 promise implementation itself sometimes calls `.then()` internally, and is unexpectedly getting the monkey-patched version, and then going into some sort of loop.

I'm still working on this. Filing bug in case anyone knows anything.

### PR DESCRIPTION
**Pull request by kentonv**
When using Promises, a callback passed to .then() will sometimes pass through multiple .then() calls. If we aren't careful, we may end up wrapping a callback multiple times, resulting in a callback that creates a fiber which immediately creates another fiber and so on.

This is especially bad because in this chain situation of fibers-creating-fibers, none of the fibers complete before others are created, thus they force expansion of the fiber pool.

This, in turn, runs into a v8 bug in which each fiber created makes fiber-switching permanently slower, due to use of a linked list. See: https://github.com/meteor/meteor/issues/7747

This change simply adds a field to the wrapped callbacks that marks them as not needing further wrapping.

Fixes #10

### CODE REVIEW

**Comment by kentonv** [comment]
I would appreciate if this could either rapidly find its way into a Meteor point release or if you could instruct me on how to force Meteor to use this patch in our build. This bug is causing repeated production outages, and although I have hotfixed it for now by editing the code in-place on the server, that's obviously not a sustainable solution.

Thanks!

**Comment by benjamn** [comment]
Fortunately, this should only require a minor version bump for the Meteor `promise` package, which can then be released independently, and Meteor 1.4 users will be able to run `meteor update promise`, thanks to version unpinning.

**Comment by kentonv** [comment]
Great! When can we expect to see that?

**Comment by kentonv** [comment]
We usually cut releases on Fridays. Will you have a chance to publish this before then?

**Comment by abernix** [comment]
@kentonv Not sure if you got a chance to try this last Friday, but the Meteor `promise` package should be updated with this pull now.  If you haven't tried it already, try updating your `promise` package to `0.8.7` – you should be able to just do `meteor update promise`!

**Comment by kentonv** [comment]
@abernix Yep, I caught it last week and it made it into our release. Thanks!

**Comment by deanius** [comment]
Nice catch @kentonv , and great write-up on Sandstorm

**Pull request merged**
